In [1]:
import numpy as np
import pandas as pd
import os
import re
import matplotlib.pyplot as plt
from matplotlib import image
import seaborn as sns

In [2]:
df = pd.read_csv("Desktop/data/creditcard.csv")

df

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V21       V22  \
0       0.462388  0.239599  0.098698  0.363787  ... -0.018307  0.277838   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.247998  0.771679   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.108300  0.005274   
4       0.095921  0.592941 -0.270533  0.817739  ... -0.009431  0.798278   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  0.213454  0.111864   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.214205  0.924384   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.232045  0.578229   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.265245  0.800049   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.261057  0.643078   

             V23       V24       V25       V26       V27       V28  Amount  \
0      -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62   
1       0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69   
2       0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66   
3      -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50   
4      -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99   
...          ...       ...       ...       ...       ...       ...     ...   
284802  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731    0.77   
284803  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   24.79   
284804 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   67.88   
284805 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   10.00   
284806  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649  217.00   

        Class  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
284802      0  
284803      0  
284804      0  
284805      0  
284806      0  

[284807 rows x 31 columns]

In [3]:
df.duplicated().value_counts()

False    283726
True       1081
dtype: int64

In [4]:
df.drop_duplicates(inplace=True)

In [5]:
df.duplicated().value_counts()

False    283726
dtype: int64

In [6]:
df['Class'].unique()

array([0, 1], dtype=int64)

In [7]:
X=df.drop("Class",axis=1)
y=df["Class"]

In [8]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=100)

In [10]:
# Data-preprocessing: Standardizing the data

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_transformed = scaler.fit_transform(X_train)
print(X_train_transformed.shape)

(198608, 30)


In [11]:
X_test_transformed = scaler.transform(X_test)
print(X_test_transformed.shape)

(85118, 30)


# Logistic regression

In [12]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train_transformed, y_train)

LogisticRegression()

In [13]:
y_test_pred = classifier.predict(X_test_transformed)

In [20]:
from sklearn import metrics

metrics.accuracy_score(y_test, y_test_pred)

0.999177612255927

In [15]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score, recall_score,classification_report

In [16]:
print(confusion_matrix(y_test,y_test_pred))

[[84956     9]
 [   61    92]]


In [17]:
print(precision_score(y_test,y_test_pred))

0.9108910891089109


In [18]:
print(recall_score(y_test,y_test_pred))

0.6013071895424836


In [19]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     84965
           1       0.91      0.60      0.72       153

    accuracy                           1.00     85118
   macro avg       0.96      0.80      0.86     85118
weighted avg       1.00      1.00      1.00     85118



## change sample size 

In [29]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.4,random_state=100)

In [30]:
# Data-preprocessing: Standardizing the data

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_transformed = scaler.fit_transform(X_train)
print(X_train_transformed.shape)

(170235, 30)


In [31]:
X_test_transformed = scaler.transform(X_test)
print(X_test_transformed.shape)

(113491, 30)


In [32]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train_transformed, y_train)

LogisticRegression()

In [33]:
y_test_pred = classifier.predict(X_test_transformed)

In [34]:
from sklearn import metrics

metrics.accuracy_score(y_test, y_test_pred)

0.9990836277766519

In [35]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score, recall_score,classification_report

In [36]:
print(confusion_matrix(y_test,y_test_pred))

[[113273     10]
 [    94    114]]


In [37]:
print(precision_score(y_test,y_test_pred))

0.9193548387096774


In [38]:
print(recall_score(y_test,y_test_pred))

0.5480769230769231


In [39]:
print(classification_report(y_test,y_test_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    113283
           1       0.92      0.55      0.69       208

    accuracy                           1.00    113491
   macro avg       0.96      0.77      0.84    113491
weighted avg       1.00      1.00      1.00    113491



# Random Forest Classification

In [22]:
%%time
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(X_train,y_train)

CPU times: total: 2min 56s
Wall time: 3min 5s


RandomForestClassifier()

In [23]:
y_pred_rfc=rfc.predict(X_test)
y_pred_rfc

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [24]:
accuracy_score(y_test,y_pred_rfc)

0.9995183157499001

In [25]:
print(confusion_matrix(y_test,y_pred_rfc))

[[84954    11]
 [   30   123]]


In [26]:
print(precision_score(y_test,y_pred_rfc))

0.917910447761194


In [27]:
print(recall_score(y_test,y_pred_rfc))

0.803921568627451


In [28]:
print(classification_report(y_test,y_pred_rfc))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     84965
           1       0.92      0.80      0.86       153

    accuracy                           1.00     85118
   macro avg       0.96      0.90      0.93     85118
weighted avg       1.00      1.00      1.00     85118

